#!/usr/bin/env python3
"""Add batch 4 commands toward 500+ total."""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1] / "CADCommands/Data/commands.json"

EXTRA = [
    {"id": "aibox", "name": "AI_BOX", "aliases": [], "category": "3D", "description": "Creates a 3D solid box using the classic primitive workflow.", "usage": "AI_BOX", "example": "Specify corner points and height.", "tips": "BOX command offers the same capability with modern prompts.", "isFree": False},
    {"id": "aicone", "name": "AI_CONE", "aliases": [], "category": "3D", "description": "Creates a 3D cone primitive from base and height values.", "usage": "AI_CONE", "example": "Define base center, radius, and height.", "tips": "Use CONE for the current equivalent tool.", "isFree": False},
    {"id": "aicyl", "name": "AI_CYL", "aliases": [], "category": "3D", "description": "Creates a 3D cylinder primitive.", "usage": "AI_CYL", "example": "Specify base, radius, and height.", "tips": "CYLINDER is the modern matching command.", "isFree": False},
    {"id": "aisphere", "name": "AI_SPHERE", "aliases": [], "category": "3D", "description": "Creates a 3D sphere primitive.", "usage": "AI_SPHERE", "example": "Pick center and radius.", "tips": "SPHERE provides the same result.", "isFree": False},
    {"id": "aitorus", "name": "AI_TORUS", "aliases": [], "category": "3D", "description": "Creates a 3D torus primitive.", "usage": "AI_TORUS", "example": "Define center, torus radius, and tube radius.", "tips": "Use TORUS in current workflows.", "isFree": False},
    {"id": "aiwedge", "name": "AI_WEDGE", "aliases": [], "category": "3D", "description": "Creates a 3D wedge primitive.", "usage": "AI_WEDGE", "example": "Specify base rectangle and height.", "tips": "WEDGE is the modern equivalent.", "isFree": False},
    {"id": "aipyramid", "name": "AI_PYRAMID", "aliases": [], "category": "3D", "description": "Creates a 3D pyramid primitive.", "usage": "AI_PYRAMID", "example": "Set sides, base, and height.", "tips": "PYRAMID command replaces this workflow.", "isFree": False},
    {"id": "aidome", "name": "AI_DOME", "aliases": [], "category": "3D", "description": "Creates a dome-shaped 3D solid.", "usage": "AI_DOME", "example": "Define base circle and dome height.", "tips": "Legacy primitive; REVOLVE can model similar shapes.", "isFree": False},
    {"id": "aidish", "name": "AI_DISH", "aliases": [], "category": "3D", "description": "Creates a dish-shaped 3D solid.", "usage": "AI_DISH", "example": "Specify base and depth parameters.", "tips": "Legacy primitive for bowl-like forms.", "isFree": False},
    {"id": "3dmesh", "name": "3DMESH", "aliases": [], "category": "3D", "description": "Creates a 3D mesh surface from a grid of vertices.", "usage": "3DMESH", "example": "Enter M and N mesh size, then vertex heights.", "tips": "Legacy tool; MESH commands are more flexible today.", "isFree": False},
    {"id": "pface", "name": "PFACE", "aliases": [], "category": "3D", "description": "Creates a 3D mesh face defined by vertex points.", "usage": "PFACE", "example": "Enter vertex numbers for each face corner.", "tips": "Older mesh face creation method.", "isFree": False},
    {"id": "convtonurbs", "name": "CONVTONURBS", "aliases": [], "category": "3D", "description": "Converts eligible objects to NURBS surfaces.", "usage": "CONVTONURBS", "example": "Select solids or surfaces to convert.", "tips": "Use when downstream tools require NURBS data.", "isFree": False},
    {"id": "meshcap", "name": "MESHCAP", "aliases": [], "category": "3D", "description": "Closes open edges of a mesh with a cover face.", "usage": "MESHCAP", "example": "Select open mesh edges to cap.", "tips": "Creates watertight meshes for printing.", "isFree": False},
    {"id": "meshextrude", "name": "MESHEXTRUDE", "aliases": [], "category": "3D", "description": "Extrudes mesh faces to add depth.", "usage": "MESHEXTRUDE", "example": "Select mesh faces and extrusion height.", "tips": "Useful for adding thickness to mesh panels.", "isFree": False},
    {"id": "meshcollapse", "name": "MESHCOLLAPSE", "aliases": [], "category": "3D", "description": "Collapses mesh faces or edges to simplify geometry.", "usage": "MESHCOLLAPSE", "example": "Select mesh subobjects to collapse.", "tips": "Reduce complexity before export.", "isFree": False},
    {"id": "meshspin", "name": "MESHSPIN", "aliases": [], "category": "3D", "description": "Revolves mesh geometry around an axis.", "usage": "MESHSPIN", "example": "Select mesh profile and axis.", "tips": "Creates revolved mesh forms.", "isFree": False},
    {"id": "meshcrease", "name": "MESHCREASE", "aliases": [], "category": "3D", "description": "Applies crease edges to control mesh smoothing.", "usage": "MESHCREASE", "example": "Select mesh edges and crease level.", "tips": "Sharpen edges on smoothed meshes.", "isFree": False},
    {"id": "meshuncrease", "name": "MESHUNCREASE", "aliases": [], "category": "3D", "description": "Removes crease settings from mesh edges.", "usage": "MESHUNCREASE", "example": "Select creased edges to smooth.", "tips": "Restore smooth transitions on mesh edges.", "isFree": False},
    {"id": "surfblend", "name": "SURFBLEND", "aliases": [], "category": "3D", "description": "Creates a smooth blend surface between two surfaces.", "usage": "SURFBLEND", "example": "Select two surfaces and blend constraints.", "tips": "Useful for filleted surface transitions.", "isFree": False},
    {"id": "surfpatch", "name": "SURFPATCH", "aliases": [], "category": "3D", "description": "Creates a surface that fills a boundary loop.", "usage": "SURFPATCH", "example": "Select boundary edges or curves.", "tips": "Closes gaps in surface models.", "isFree": False},
    {"id": "surfnetwork", "name": "SURFNETWORK", "aliases": [], "category": "3D", "description": "Creates a surface from a network of crossing curves.", "usage": "SURFNETWORK", "example": "Select U and V direction curves.", "tips": "Requires well-defined curve networks.", "isFree": False},
    {"id": "surfsculpt", "name": "SURFSCULPT", "aliases": [], "category": "3D", "description": "Combines intersecting surfaces into a sculptured solid.", "usage": "SURFSCULPT", "example": "Select surfaces that enclose a volume.", "tips": "Automates closing surface envelopes.", "isFree": False},
    {"id": "surfoffset", "name": "SURFOFFSET", "aliases": [], "category": "3D", "description": "Offsets a surface by a specified distance.", "usage": "SURFOFFSET", "example": "Select surface and offset distance.", "tips": "Check normal direction for offset side.", "isFree": False},
    {"id": "surfuntrim", "name": "SURFUNTRIM", "aliases": [], "category": "3D", "description": "Removes trimmed areas from surfaces.", "usage": "SURFUNTRIM", "example": "Select surface and regions to untrim.", "tips": "Restore surface area after trimming.", "isFree": False},
    {"id": "solprof", "name": "SOLPROF", "aliases": [], "category": "3D", "description": "Creates profile blocks from 3D solids in layout viewports.", "usage": "SOLPROF", "example": "Select solids while in paper space viewport.", "tips": "Generates 2D linework from 3D models.", "isFree": False},
    {"id": "mslice", "name": "MSLICE", "aliases": [], "category": "3D", "description": "Slices a solid using a plane and optionally keeps both halves.", "usage": "MSLICE", "example": "Select solid and define slicing plane.", "tips": "Similar to SLICE with multi-body options.", "isFree": False},
    {"id": "viewproj", "name": "VIEWPROJ", "aliases": [], "category": "3D", "description": "Projects geometry from one view to another.", "usage": "VIEWPROJ", "example": "Select source view and projection target.", "tips": "Used in automated drawing view workflows.", "isFree": False},
    {"id": "viewupdate", "name": "VIEWUPDATE", "aliases": [], "category": "3D", "description": "Updates drawing views after model changes.", "usage": "VIEWUPDATE", "example": "Select views to refresh from model.", "tips": "Run after editing 3D source geometry.", "isFree": False},
    {"id": "viewgo", "name": "VIEWGO", "aliases": [], "category": "View & Navigation", "description": "Restores a named view instantly.", "usage": "VIEWGO", "example": "Choose saved view from list.", "tips": "Fast navigation between preset views.", "isFree": False},
    {"id": "showmotion", "name": "SHOWMOTION", "aliases": [], "category": "View & Navigation", "description": "Plays recorded view animations and walkthroughs.", "usage": "SHOWMOTION", "example": "Select animation from the list.", "tips": "Use for client presentation playback.", "isFree": False},
    {"id": "rtzoom", "name": "RTZOOM", "aliases": [], "category": "View & Navigation", "description": "Zooms the view interactively in real time.", "usage": "RTZOOM", "example": "Drag up or down to zoom dynamically.", "tips": "Legacy realtime navigation command.", "isFree": False},
    {"id": "rtpan", "name": "RTPAN", "aliases": [], "category": "View & Navigation", "description": "Pans the view interactively in real time.", "usage": "RTPAN", "example": "Drag to pan the drawing.", "tips": "Mouse wheel drag pan is faster today.", "isFree": False},
    {"id": "realtime", "name": "REALTIME", "aliases": ["R"], "category": "View & Navigation", "description": "Starts realtime zoom and pan navigation.", "usage": "REALTIME", "example": "Right-click to switch zoom or pan mode.", "tips": "Superseded by mouse wheel navigation.", "isFree": False},
    {"id": "elevation", "name": "ELEV", "aliases": [], "category": "Settings & System", "description": "Sets default elevation and extrusion thickness for new objects.", "usage": "ELEV", "example": "Enter elevation and thickness values.", "tips": "Less common with modern 3D workflows.", "isFree": False},
    {"id": "thickness", "name": "THICKNESS", "aliases": [], "category": "Settings & System", "description": "Sets default 3D thickness for new 2D objects.", "usage": "THICKNESS", "example": "Enter thickness at command line.", "tips": "Legacy setting for pseudo-3D linework.", "isFree": False},
    {"id": "ucsdetect", "name": "UCSDETECT", "aliases": [], "category": "View & Navigation", "description": "Automatically aligns UCS to detected faces.", "usage": "UCSDETECT", "example": "Hover over a face to preview UCS alignment.", "tips": "Speeds 3D sketching on angled faces.", "isFree": False},
    {"id": "worlducs", "name": "UCS WORLD", "aliases": [], "category": "View & Navigation", "description": "Restores the World Coordinate System.", "usage": "UCS W", "example": "Type UCS, then W for World.", "tips": "Return to default coordinates after angled work.", "isFree": False},
    {"id": "layout", "name": "LAYOUT", "aliases": ["LO"], "category": "View & Navigation", "description": "Creates and modifies layout tabs for plotting.", "usage": "LAYOUT", "example": "Create new layout or rename existing tabs.", "tips": "Sheets for title blocks and viewports live here.", "isFree": False},
    {"id": "layoutcreate", "name": "LAYOUTCREATE", "aliases": [], "category": "View & Navigation", "description": "Creates a new layout tab from a template.", "usage": "LAYOUTCREATE", "example": "Choose template and layout name.", "tips": "Standardize new sheets across projects.", "isFree": False},
    {"id": "psetupin", "name": "PSETUPIN", "aliases": [], "category": "Settings & System", "description": "Imports page setup into the current layout.", "usage": "PSETUPIN", "example": "Select source drawing and page setup name.", "tips": "Reuse plot settings from other files.", "isFree": False},
    {"id": "screenshot", "name": "SCREENSHOT", "aliases": [], "category": "Settings & System", "description": "Captures the current viewport as an image file.", "usage": "SCREENSHOT", "example": "Choose save location and image format.", "tips": "Quick way to share on-screen views.", "isFree": False},
    {"id": "about", "name": "ABOUT", "aliases": [], "category": "Settings & System", "description": "Displays product version and license information.", "usage": "ABOUT", "example": "Run to view application about dialog.", "tips": "Verify version when troubleshooting compatibility.", "isFree": False},
    {"id": "aliasedit", "name": "ALIASEDIT", "aliases": [], "category": "Settings & System", "description": "Edits command alias definitions in the acad.pgp file.", "usage": "ALIASEDIT", "example": "Modify shortcut to command mappings.", "tips": "Customize keyboard shortcuts for speed.", "isFree": False},
    {"id": "bcount", "name": "BCOUNT", "aliases": [], "category": "Inquiry", "description": "Counts block instances and reports totals in the text window.", "usage": "BCOUNT", "example": "Select blocks or count entire drawing.", "tips": "Text-window alternative to COUNT command.", "isFree": False},
    {"id": "brep", "name": "BREP", "aliases": [], "category": "3D", "description": "Converts a 3D solid to a boundary representation form.", "usage": "BREP", "example": "Select solid objects to convert.", "tips": "Used in advanced solid exchange workflows.", "isFree": False},
    {"id": "bmod", "name": "BMOD", "aliases": [], "category": "Blocks & References", "description": "Opens the Block Editor for a selected block reference.", "usage": "BMOD", "example": "Select block and edit definition in place.", "tips": "Shortcut workflow similar to BEDIT.", "isFree": False},
    {"id": "checkstandards", "name": "CHECKSTANDARDS", "aliases": [], "category": "Layers & Properties", "description": "Checks drawing objects against CAD standards.", "usage": "CHECKSTANDARDS", "example": "Run audit and review violations list.", "tips": "Enforce office layer and style rules.", "isFree": False},
    {"id": "laystd", "name": "LAYSTD", "aliases": [], "category": "Layers & Properties", "description": "Manages layer standards and translation mappings.", "usage": "LAYSTD", "example": "Define or apply layer standard rules.", "tips": "Pair with CHECKSTANDARDS for compliance.", "isFree": False},
    {"id": "standards", "name": "STANDARDS", "aliases": [], "category": "Layers & Properties", "description": "Associates the drawing with a CAD standards file.", "usage": "STANDARDS", "example": "Attach DWS file and configure checks.", "tips": "Centralize rules for multi-user teams.", "isFree": False},
    {"id": "attdisp", "name": "ATTDISP", "aliases": [], "category": "Blocks & References", "description": "Controls visibility of block attribute values.", "usage": "ATTDISP", "example": "Set Normal, On, or Off display mode.", "tips": "Hide attributes temporarily without deleting them.", "isFree": False},
    {"id": "attreq", "name": "ATTREQ", "aliases": [], "category": "Blocks & References", "description": "Controls whether attribute values are prompted during INSERT.", "usage": "ATTREQ", "example": "Set to 1 to prompt, 0 to use defaults.", "tips": "Speed up insertion when defaults are fine.", "isFree": False},
    {"id": "attipedit", "name": "ATTIPEDIT", "aliases": [], "category": "Blocks & References", "description": "Edits block attribute text in place on screen.", "usage": "ATTIPEDIT", "example": "Double-click attribute text to edit.", "tips": "Fast title block and tag updates.", "isFree": False},
    {"id": "fieldeval", "name": "FIELDEVAL", "aliases": [], "category": "Annotation", "description": "Controls when fields are evaluated and updated.", "usage": "FIELDEVAL", "example": "Set evaluation timing bitmask value.", "tips": "Adjust if fields seem stale on plot.", "isFree": False},
    {"id": "mtedit", "name": "MTEDIT", "aliases": [], "category": "Annotation", "description": "Edits multiline text in a dedicated editor.", "usage": "MTEDIT", "example": "Select mtext object to open editor.", "tips": "Double-click mtext for the same result.", "isFree": False},
    {"id": "textscr", "name": "TEXTSCR", "aliases": [], "category": "Settings & System", "description": "Opens the text window for command history review.", "usage": "TEXTSCR", "aliases": [], "example": "Toggle text window open or closed.", "tips": "F2 also opens the text window.", "isFree": False},
    {"id": "arctext", "name": "ARCTEXT", "aliases": [], "category": "Annotation", "description": "Aligns text along an arc curve.", "usage": "ARCTEXT", "example": "Select arc and enter text content.", "tips": "Express tool for curved labels.", "isFree": False},
    {"id": "txtexp", "name": "TXTEXP", "aliases": [], "category": "Annotation", "description": "Explodes text into individual polyline outlines.", "usage": "TXTEXP", "example": "Select text objects to explode.", "tips": "Express tool for CNC or laser workflows.", "isFree": False},
    {"id": "tscale", "name": "TSCALE", "aliases": [], "category": "Annotation", "description": "Scales text without changing insertion point.", "usage": "TSCALE", "example": "Select text and scale factor.", "tips": "Express tool for quick text resizing.", "isFree": False},
    {"id": "laypick", "name": "LAYPICK", "aliases": [], "category": "Layers & Properties", "description": "Sets current layer by picking an object on that layer.", "usage": "LAYPICK", "example": "Pick any object to match its layer.", "tips": "Express tool similar to LAYMCUR.", "isFree": False},
    {"id": "layerf", "name": "LAYERF", "aliases": [], "category": "Layers & Properties", "description": "Freezes layers of selected objects quickly.", "usage": "LAYERF", "example": "Select object on layer to freeze.", "tips": "Express tool similar to LAYFRZ.", "isFree": False},
    {"id": "flatten", "name": "FLATTEN", "aliases": [], "category": "3D", "description": "Projects geometry to a uniform elevation.", "usage": "FLATTEN", "example": "Select objects and confirm flatten.", "tips": "Express tool for 2D cleanup of 3D exports.", "isFree": False},
    {"id": "exoffset", "name": "EXOFFSET", "aliases": [], "category": "Modifying", "description": "Offsets objects with extended options.", "usage": "EXOFFSET", "example": "Select object and offset distance.", "tips": "Express tool variant of OFFSET.", "isFree": False},
    {"id": "getsel", "name": "GETSEL", "aliases": [], "category": "Inquiry", "description": "Reports the number of objects in the current selection.", "usage": "GETSEL", "example": "Run after selecting objects.", "tips": "Express tool for quick selection counts.", "isFree": False},
    {"id": "sysvdlg", "name": "SYSVDLG", "aliases": [], "category": "Settings & System", "description": "Opens a dialog to browse and edit system variables.", "usage": "SYSVDLG", "example": "Search variable name and change value.", "tips": "Easier than memorizing variable names.", "isFree": False},
    {"id": "setvar", "name": "SETVAR", "aliases": [], "category": "Settings & System", "description": "Sets the value of a system variable.", "usage": "SETVAR", "example": "Enter variable name and new value.", "tips": "Many settings are controlled via system variables.", "isFree": False},
    {"id": "getvar", "name": "GETVAR", "aliases": [], "category": "Inquiry", "description": "Reports the current value of a system variable.", "usage": "GETVAR", "example": "Enter variable name at prompt.", "tips": "Quick way to inspect drawing settings.", "isFree": False},
    {"id": "cmdecho", "name": "CMDECHO", "aliases": [], "category": "Settings & System", "description": "Controls whether commands echo to the text window during scripts.", "usage": "CMDECHO", "example": "Set to 0 to suppress echo in scripts.", "tips": "Useful when running SCR files.", "isFree": False},
    {"id": "filedia", "name": "FILEDIA", "aliases": [], "category": "Settings & System", "description": "Toggles file dialog boxes for open and save commands.", "usage": "FILEDIA", "example": "Set to 1 for dialogs, 0 for command line.", "tips": "Set to 0 in automation scripts.", "isFree": False},
    {"id": "menubar", "name": "MENUBAR", "aliases": [], "category": "Settings & System", "description": "Displays or hides the menu bar above the ribbon.", "usage": "MENUBAR", "example": "Set to 1 to show, 0 to hide.", "tips": "Some users prefer classic menu access.", "isFree": False},
    {"id": "mirrtext", "name": "MIRRTEXT", "aliases": [], "category": "Settings & System", "description": "Controls whether text is mirrored with the MIRROR command.", "usage": "MIRRTEXT", "example": "Set to 0 to keep text readable after mirror.", "tips": "Set 0 for standard readable annotations.", "isFree": False},
    {"id": "pickadd", "name": "PICKADD", "aliases": [], "category": "Settings & System", "description": "Controls whether subsequent selections add to the set.", "usage": "PICKADD", "example": "Set to 2 for additive selection behavior.", "tips": "Affects shift-select behavior.", "isFree": False},
    {"id": "pickauto", "name": "PICKAUTO", "aliases": [], "category": "Settings & System", "description": "Controls automatic selection at blank pick points.", "usage": "PICKAUTO", "example": "Set to 1 to enable auto window selection.", "tips": "Adjust if accidental selections occur.", "isFree": False},
    {"id": "pickfirst", "name": "PICKFIRST", "aliases": [], "category": "Settings & System", "description": "Controls whether objects must be selected before commands.", "usage": "PICKFIRST", "example": "Set to 1 for select-first workflow.", "tips": "Most users prefer pick-first enabled.", "isFree": False},
    {"id": "pickstyle", "name": "PICKSTYLE", "aliases": [], "category": "Settings & System", "description": "Controls group and hatch associative selection behavior.", "usage": "PICKSTYLE", "example": "Set bitcode for group and hatch selection.", "tips": "Adjust if hatches select with boundaries.", "isFree": False},
    {"id": "xloadctl", "name": "XLOADCTL", "aliases": [], "category": "Blocks & References", "description": "Controls demand loading of xref references.", "usage": "XLOADCTL", "example": "Set value for load on open or demand.", "tips": "Affects performance with many xrefs.", "isFree": False},
    {"id": "xrefnotify", "name": "XREFNOTIFY", "aliases": [], "category": "Blocks & References", "description": "Controls notification when xrefs change on disk.", "usage": "XREFNOTIFY", "example": "Set to 2 to enable reload notifications.", "tips": "Stay aware of consultant file updates.", "isFree": False},
    {"id": "xrepath", "name": "XREPATH", "aliases": [], "category": "Blocks & References", "description": "Changes the path of xref and image references.", "usage": "XREPATH", "example": "Select references and enter new path.", "tips": "Fix broken xref paths after folder moves.", "isFree": False},
    {"id": "underlay", "name": "UNDERLAY", "aliases": [], "category": "Blocks & References", "description": "Manages attached underlay references such as PDF and DWF.", "usage": "UNDERLAY", "example": "Attach, clip, or adjust underlay settings.", "tips": "Central tool for PDF and DWF references.", "isFree": False},
    {"id": "dgnexport", "name": "DGNEXPORT", "aliases": [], "category": "Settings & System", "description": "Exports the drawing to MicroStation DGN format.", "usage": "DGNEXPORT", "example": "Choose version and export options.", "tips": "Common for civil infrastructure exchange.", "isFree": False},
    {"id": "dwgconvert", "name": "DWGCONVERT", "aliases": [], "category": "Settings & System", "description": "Batch converts drawings to another DWG version.", "usage": "DWGCONVERT", "example": "Add files and target format version.", "tips": "Prepare files for older software versions.", "isFree": False},
    {"id": "digitalsign", "name": "DIGITALSIGN", "aliases": [], "category": "Settings & System", "description": "Applies a digital signature to the drawing file.", "usage": "DIGITALSIGN", "example": "Select certificate and sign drawing.", "tips": "Used for authenticated submittals.", "isFree": False},
    {"id": "reinit", "name": "REINIT", "aliases": [], "category": "Settings & System", "description": "Reinitializes digitizer, tablet, and input devices.", "usage": "REINIT", "example": "Select devices to reinitialize.", "tips": "Troubleshoot input device issues.", "isFree": False},
    {"id": "logfileon", "name": "LOGFILEON", "aliases": [], "category": "Settings & System", "description": "Starts logging command text to a file.", "usage": "LOGFILEON", "example": "Specify log file path.", "tips": "Use LOGFILEOFF to stop logging.", "isFree": False},
    {"id": "logfileoff", "name": "LOGFILEOFF", "aliases": [], "category": "Settings & System", "description": "Stops logging command text to a file.", "usage": "LOGFILEOFF", "example": "Run to close active log session.", "tips": "Pair with LOGFILEON for session logs.", "isFree": False},
    {"id": "newsheetset", "name": "NEWSHEETSET", "aliases": [], "category": "Settings & System", "description": "Creates a new sheet set for organized publishing.", "usage": "NEWSHEETSET", "example": "Follow wizard to define sheet set.", "tips": "Start of sheet set management workflow.", "isFree": False},
    {"id": "opensheetset", "name": "OPENSHEETSET", "aliases": [], "category": "Settings & System", "description": "Opens an existing sheet set for editing.", "usage": "OPENSHEETSET", "example": "Browse to DST file and open.", "tips": "Access previously configured sheet sets.", "isFree": False},
    {"id": "toolbars", "name": "TOOLBAR", "aliases": [], "category": "Settings & System", "description": "Displays or hides named toolbars.", "usage": "TOOLBAR", "example": "Enter toolbar name and show option.", "tips": "Legacy UI; ribbon replaced most toolbars.", "isFree": False},
    {"id": "menuload", "name": "MENULOAD", "aliases": [], "category": "Settings & System", "description": "Loads or unloads partial menu files.", "usage": "MENULOAD", "example": "Select MNU or CUI partial menu.", "tips": "Customize interface with partial menus.", "isFree": False},
    {"id": "wssettings", "name": "WSSETTINGS", "aliases": [], "category": "Settings & System", "description": "Configures workspace behavior and save options.", "usage": "WSSETTINGS", "example": "Adjust auto-save and switch settings.", "tips": "Control how workspaces persist.", "isFree": False},
    {"id": "dline", "name": "DLINE", "aliases": [], "category": "Drawing", "description": "Creates double parallel lines using a dedicated tool.", "usage": "DLINE", "example": "Pick points to draw double-line paths.", "tips": "MLINE is the modern replacement.", "isFree": False},
    {"id": "donut", "name": "DONUT", "aliases": ["DO"], "category": "Drawing", "description": "Draws filled rings or circles with inside and outside diameters.", "usage": "DONUT", "example": "Enter inside and outside diameters.", "tips": "Set inside diameter to zero for solid dots.", "isFree": False},
    {"id": "copylink", "name": "COPYLINK", "aliases": [], "category": "Settings & System", "description": "Copies drawing objects with a link to the source file.", "usage": "COPYLINK", "example": "Select objects and destination application.", "tips": "Legacy OLE linking workflow.", "isFree": False},
    {"id": "date", "name": "DATE", "aliases": [], "category": "Inquiry", "description": "Displays the current date and time.", "usage": "DATE", "example": "Run to view system date in text window.", "tips": "Useful when documenting session notes.", "isFree": False},
    {"id": "whiparc", "name": "WHIPARC", "aliases": [], "category": "View & Navigation", "description": "Controls whether arcs appear smooth or segmented.", "usage": "WHIPARC", "example": "Set to 1 for smooth arc display.", "tips": "Turn off on slow hardware if needed.", "isFree": False},
    {"id": "vtoptions", "name": "VTOPTIONS", "aliases": [], "category": "View & Navigation", "description": "Sets view transition and pan/zoom animation options.", "usage": "VTOPTIONS", "example": "Adjust smooth transition settings.", "tips": "Disable if motion causes discomfort.", "isFree": False},
    {"id": "secureload", "name": "SECURELOAD", "aliases": [], "category": "Settings & System", "description": "Controls whether executable files load from unsafe paths.", "usage": "SECURELOAD", "example": "Set security level for LISP and apps.", "tips": "Keep enabled for safer customization.", "isFree": False},
    {"id": "trustedpaths", "name": "TRUSTEDPATHS", "aliases": [], "category": "Settings & System", "description": "Defines folders trusted for loading custom files.", "usage": "TRUSTEDPATHS", "example": "Add office standard support folder paths.", "tips": "Required for loading LISP from network drives.", "isFree": False},
    {"id": "xrepath2", "name": "XREFSTATE", "aliases": [], "category": "Blocks & References", "description": "Reports whether xrefs are loaded, unloaded, or not found.", "usage": "XREFSTATE", "example": "Run and review xref status report.", "tips": "Diagnose broken reference paths quickly.", "isFree": False},
    {"id": "dimspace2", "name": "DIMSPACE", "aliases": [], "category": "Annotation", "description": "Adjusts spacing between dimensions in a linear set.", "usage": "DIMSPACE", "example": "Select base dimension then others.", "tips": "Even out crowded dimension strings.", "isFree": False},
]

def main():
    with BASE.open() as f:
        data = json.load(f)

    existing_ids = {c["id"] for c in data["commands"]}
    existing_names = {c["name"] for c in data["commands"]}

    added = []
    skipped = []
    for cmd in EXTRA:
        # fix textscr duplicate aliases key issue
        if "aliases" not in cmd:
            cmd["aliases"] = []
        if cmd["id"] in existing_ids or cmd["name"] in existing_names:
            skipped.append(cmd["name"])
            continue
        added.append(cmd)
        existing_ids.add(cmd["id"])
        existing_names.add(cmd["name"])

    data["commands"].extend(added)
    data["commands"].sort(key=lambda c: c["name"])

    with BASE.open("w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    total = len(data["commands"])
    free = sum(1 for c in data["commands"] if c["isFree"])
    print(f"added={len(added)} skipped={len(skipped)} total={total} free={free} pro={total-free} size_kb={BASE.stat().st_size/1024:.1f}")

if __name__ == "__main__":
    main()
