#!/usr/bin/env python3
import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1] / "CADCommands/Data/commands.json"

EXTRA = [
    {"id": "dimspace", "name": "DIMSPACE", "aliases": [], "category": "Annotation", "description": "Adjusts equal spacing between a series of dimensions.", "usage": "DIMSPACE", "example": "Select base dimension, then others in the set.", "tips": "Cleans crowded dimension strings quickly.", "isFree": False},
    {"id": "qblock", "name": "QBLOCK", "aliases": [], "category": "Blocks & References", "description": "Quickly creates a block from selected objects.", "usage": "QBLOCK", "example": "Select objects and enter a block name.", "tips": "Faster than the full BLOCK dialog for simple cases.", "isFree": False},
    {"id": "dimarc", "name": "DIMARC", "aliases": ["DAR"], "category": "Annotation", "description": "Creates an arc length dimension.", "usage": "DIMARC", "example": "Select an arc and place the dimension.", "tips": "Use when measuring distance along a curved edge.", "isFree": False},
    {"id": "dimjogged", "name": "DIMJOGGED", "aliases": ["DJO"], "category": "Annotation", "description": "Creates a jogged radius dimension for small arcs.", "usage": "DIMJOGGED", "example": "Select arc or circle and place jogged dimension.", "tips": "Keeps large radius callouts readable in tight views.", "isFree": False},
    {"id": "dimordinate", "name": "DIMORDINATE", "aliases": ["DOR"], "category": "Annotation", "description": "Creates ordinate X or Y dimensions from a datum.", "usage": "DIMORDINATE", "example": "Pick feature point and place dimension.", "tips": "Common in machining and CNC drawings.", "isFree": False},
    {"id": "dimrotated", "name": "DIMROTATED", "aliases": ["DRO"], "category": "Annotation", "description": "Creates a linear dimension at a specified angle.", "usage": "DIMROTATED", "example": "Pick two points and set dimension line angle.", "tips": "Use when the dimension line is not horizontal or vertical.", "isFree": False},
    {"id": "dimedit", "name": "DIMEDIT", "aliases": ["DED"], "category": "Annotation", "description": "Edits dimension text, angle, and home position.", "usage": "DIMEDIT", "example": "Select dimensions and choose edit option.", "tips": "Override text while keeping associative links.", "isFree": False},
    {"id": "dimtedit", "name": "DIMTEDIT", "aliases": ["DTE"], "category": "Annotation", "description": "Moves and rotates dimension text independently.", "usage": "DIMTEDIT", "example": "Select dimension text and reposition.", "tips": "Double-click dimension text for quick edits.", "isFree": False},
    {"id": "dimreassociate", "name": "DIMREASSOCIATE", "aliases": ["DRE"], "category": "Annotation", "description": "Rebuilds associativity between dimensions and geometry.", "usage": "DIMREASSOCIATE", "example": "Select dimensions that lost their links.", "tips": "Run after importing or exploding geometry.", "isFree": False},
    {"id": "mleaderedit", "name": "MLEADEREDIT", "aliases": [], "category": "Annotation", "description": "Edits multileader content and landing geometry.", "usage": "MLEADEREDIT", "example": "Select multileader and modify text or block.", "tips": "Use MLEADERALIGN to tidy multiple callouts.", "isFree": False},
    {"id": "mleaderalign", "name": "MLEADERALIGN", "aliases": [], "category": "Annotation", "description": "Aligns and spaces selected multileaders.", "usage": "MLEADERALIGN", "example": "Select multileaders and alignment reference.", "tips": "Clean up crowded detail annotations.", "isFree": False},
    {"id": "mleadercollect", "name": "MLEADERCOLLECT", "aliases": [], "category": "Annotation", "description": "Combines multiple multileaders into one stacked callout.", "usage": "MLEADERCOLLECT", "example": "Select multileaders to merge.", "tips": "Useful for repeated fastener or note tags.", "isFree": False},
    {"id": "mledit", "name": "MLEDIT", "aliases": [], "category": "Drawing", "description": "Edits multiline joints, cuts, and vertices.", "usage": "MLEDIT", "example": "Select multiline and choose edit operation.", "tips": "Clean wall intersections in floor plans.", "isFree": False},
    {"id": "arrayclassic", "name": "ARRAYCLASSIC", "aliases": [], "category": "Modifying", "description": "Creates arrays using the classic dialog workflow.", "usage": "ARRAYCLASSIC", "example": "Select objects and define array pattern.", "tips": "Use ARRAY for modern associative arrays.", "isFree": False},
    {"id": "distribute", "name": "DISTRIBUTE", "aliases": [], "category": "Modifying", "description": "Evenly spaces objects between two points.", "usage": "DISTRIBUTE", "example": "Select objects and distribution endpoints.", "tips": "Handy for equal spacing of fixtures or columns.", "isFree": False},
    {"id": "gcon", "name": "GCON", "aliases": [], "category": "Modifying", "description": "Applies geometric constraints between objects.", "usage": "GCON", "example": "Select objects and constraint type.", "tips": "Maintains design intent in parametric drawings.", "isFree": False},
    {"id": "delconstraint", "name": "DELCONSTRAINT", "aliases": [], "category": "Modifying", "description": "Removes geometric constraints from selected objects.", "usage": "DELCONSTRAINT", "example": "Select constrained geometry.", "tips": "Use when constraints block needed edits.", "isFree": False},
    {"id": "dimconstraint", "name": "DIMCONSTRAINT", "aliases": [], "category": "Annotation", "description": "Applies dimensional constraints that drive geometry size.", "usage": "DIMCONSTRAINT", "example": "Select objects and enter constraint value.", "tips": "Changing the value updates linked geometry.", "isFree": False},
    {"id": "dimdisassociate", "name": "DIMDISASSOCIATE", "aliases": ["DDA"], "category": "Annotation", "description": "Breaks associativity between dimensions and geometry.", "usage": "DIMDISASSOCIATE", "example": "Select associative dimensions.", "tips": "Use before moving dimensions independently.", "isFree": False},
    {"id": "diminspect", "name": "DIMINSPECT", "aliases": [], "category": "Annotation", "description": "Adds or removes inspection frames on dimension text.", "usage": "DIMINSPECT", "example": "Select dimensions and toggle inspection format.", "tips": "Used in quality-control documentation.", "isFree": False},
    {"id": "dimoverride", "name": "DIMOVERRIDE", "aliases": ["DOV"], "category": "Annotation", "description": "Sets local overrides for dimension variables.", "usage": "DIMOVERRIDE", "example": "Select dimensions and override settings.", "tips": "Clear overrides to restore dimension style.", "isFree": False},
    {"id": "baction", "name": "BACTION", "aliases": [], "category": "Blocks & References", "description": "Adds an action to a dynamic block parameter.", "usage": "BACTION", "example": "Select parameter and affected objects.", "tips": "Build dynamic blocks inside BEDIT.", "isFree": False},
    {"id": "bactionbar", "name": "BACTIONBAR", "aliases": [], "category": "Blocks & References", "description": "Shows or hides dynamic block action bars.", "usage": "BACTIONBAR", "example": "Select block reference and toggle bar.", "tips": "Hide bars for cleaner plotted output.", "isFree": False},
    {"id": "bparameter", "name": "BPARAMETER", "aliases": [], "category": "Blocks & References", "description": "Adds a parameter to a dynamic block definition.", "usage": "BPARAMETER", "example": "Choose parameter type and placement.", "tips": "Parameters create grips on block inserts.", "isFree": False},
    {"id": "blookuptable", "name": "BLOOKUPTABLE", "aliases": ["BLT"], "category": "Blocks & References", "description": "Creates lookup tables for dynamic block states.", "usage": "BLOOKUPTABLE", "example": "Define lookup properties and visibility states.", "tips": "One block can represent many symbol variants.", "isFree": False},
    {"id": "bvmode", "name": "BVMODE", "aliases": [], "category": "Blocks & References", "description": "Controls visibility of dynamic block parameter frames.", "usage": "BVMODE", "example": "Toggle parameter display in block editor.", "tips": "Turn off when frames clutter the block.", "isFree": False},
    {"id": "chamferedge", "name": "CHAMFEREDGE", "aliases": [], "category": "3D", "description": "Bevels edges on a 3D solid.", "usage": "CHAMFEREDGE", "example": "Select edges and enter chamfer distances.", "tips": "Apply to multiple edges at once.", "isFree": False},
    {"id": "filletedge", "name": "FILLETEDGE", "aliases": [], "category": "3D", "description": "Rounds edges on a 3D solid with a radius.", "usage": "FILLETEDGE", "example": "Select edges and specify radius.", "tips": "Small radii may fail on tight geometry.", "isFree": False},
    {"id": "3dprint", "name": "3DPRINT", "aliases": [], "category": "3D", "description": "Sends 3D solids to a connected printing service.", "usage": "3DPRINT", "example": "Select solids and confirm print settings.", "tips": "Verify units before sending to a printer.", "isFree": False},
    {"id": "alignspace", "name": "ALIGNSPACE", "aliases": [], "category": "View & Navigation", "description": "Aligns layout viewports to match each other.", "usage": "ALIGNSPACE", "example": "Select viewports and alignment points.", "tips": "Coordinates plan and enlarged plan views.", "isFree": False},
    {"id": "attext", "name": "ATTEXT", "aliases": [], "category": "Inquiry", "description": "Exports block attribute values to an external file.", "usage": "ATTEXT", "example": "Choose format and select blocks.", "tips": "DATAEXTRACTION offers more export options.", "isFree": False},
    {"id": "bhatch", "name": "BHATCH", "aliases": ["BH"], "category": "Drawing", "description": "Creates hatches using the classic boundary dialog.", "usage": "BHATCH", "example": "Pick points or select boundary objects.", "tips": "Similar to HATCH with dialog workflow.", "isFree": False},
    {"id": "bpoly", "name": "BPOLY", "aliases": [], "category": "Drawing", "description": "Creates a boundary polyline from an internal point.", "usage": "BPOLY", "example": "Click inside a closed area.", "tips": "Increase gap tolerance if detection fails.", "isFree": False},
    {"id": "compare", "name": "COMPARE", "aliases": [], "category": "Inquiry", "description": "Compares two drawings and highlights differences.", "usage": "COMPARE", "example": "Select baseline and comparison files.", "tips": "Speeds revision review workflows.", "isFree": False},
    {"id": "copytolayer", "name": "COPYTOLAYER", "aliases": [], "category": "Layers & Properties", "description": "Copies objects onto another layer.", "usage": "COPYTOLAYER", "example": "Select objects and destination layer.", "tips": "Duplicate geometry onto detail layers.", "isFree": False},
    {"id": "dgnimport", "name": "DGNIMPORT", "aliases": [], "category": "Settings & System", "description": "Imports a DGN file into the current drawing.", "usage": "DGNIMPORT", "example": "Select file and layer mapping.", "tips": "Verify units after import.", "isFree": False},
    {"id": "dview", "name": "DVIEW", "aliases": [], "category": "View & Navigation", "description": "Sets camera and target for viewing direction.", "usage": "DVIEW", "example": "Select objects and define camera points.", "tips": "Legacy alternative to modern view tools.", "isFree": False},
    {"id": "edge", "name": "EDGE", "aliases": [], "category": "3D", "description": "Shows or hides edges on 3D surfaces and solids.", "usage": "EDGE", "example": "Select edges and visibility option.", "tips": "Hide interior edges for cleaner shaded views.", "isFree": False},
    {"id": "exportlayout", "name": "EXPORTLAYOUT", "aliases": [], "category": "Settings & System", "description": "Exports a layout tab to model space or a new file.", "usage": "EXPORTLAYOUT", "example": "Choose layout and destination.", "tips": "Flatten sheet content for sharing.", "isFree": False},
    {"id": "exportpdf", "name": "EXPORTPDF", "aliases": [], "category": "Settings & System", "description": "Exports selected layouts to PDF.", "usage": "EXPORTPDF", "example": "Pick sheets and output folder.", "tips": "Often faster than legacy plot-to-PDF.", "isFree": False},
    {"id": "geographiclocation", "name": "GEOGRAPHICLOCATION", "aliases": [], "category": "Settings & System", "description": "Sets geographic coordinates and north direction.", "usage": "GEOGRAPHICLOCATION", "example": "Enter coordinates or pick from map.", "tips": "Required for geolocation map workflows.", "isFree": False},
    {"id": "geomark", "name": "GEOMARK", "aliases": [], "category": "Inquiry", "description": "Places labeled marks for measured geometry values.", "usage": "GEOMARK", "example": "Measure a value and place a mark.", "tips": "Useful for coordination review notes.", "isFree": False},
    {"id": "gizmo", "name": "GIZMO", "aliases": [], "category": "3D", "description": "Toggles 3D move, rotate, and scale gizmos.", "usage": "GIZMO", "example": "Enable or disable gizmo display.", "tips": "Turn off when gizmos obscure small parts.", "isFree": False},
    {"id": "groupedit", "name": "GROUPEDIT", "aliases": [], "category": "Blocks & References", "description": "Adds or removes objects from a group.", "usage": "GROUPEDIT", "example": "Select group and add or remove members.", "tips": "Edit groups without exploding them.", "isFree": False},
    {"id": "hatchgenerateboundary", "name": "HATCHGENERATEBOUNDARY", "aliases": [], "category": "Drawing", "description": "Regenerates the boundary of an existing hatch.", "usage": "HATCHGENERATEBOUNDARY", "example": "Select hatch object.", "tips": "Use when hatch boundaries become invalid.", "isFree": False},
    {"id": "hatchsetorigin", "name": "HATCHSETORIGIN", "aliases": [], "category": "Drawing", "description": "Sets hatch pattern origin for alignment.", "usage": "HATCHSETORIGIN", "example": "Select hatch and pick origin.", "tips": "Align patterns across adjacent rooms.", "isFree": False},
    {"id": "laytrans", "name": "LAYTRANS", "aliases": [], "category": "Layers & Properties", "description": "Translates foreign layers to local standards.", "usage": "LAYTRANS", "example": "Load translation map and apply.", "tips": "Essential for imported consultant files.", "isFree": False},
    {"id": "layvpi", "name": "LAYVPI", "aliases": [], "category": "Layers & Properties", "description": "Controls viewport-specific layer overrides.", "usage": "LAYVPI", "example": "Select viewport and override properties.", "tips": "Different display per viewport if needed.", "isFree": False},
    {"id": "leaderedit", "name": "LEADEREDIT", "aliases": [], "category": "Annotation", "description": "Edits legacy leader text and vertices.", "usage": "LEADEREDIT", "example": "Select leader and modify content.", "tips": "For older leader objects.", "isFree": False},
    {"id": "lightlist", "name": "LIGHTLIST", "aliases": [], "category": "3D", "description": "Lists and edits lights in the drawing.", "usage": "LIGHTLIST", "example": "Adjust intensity in the light palette.", "tips": "Disable unused lights to speed rendering.", "isFree": False},
    {"id": "markup", "name": "MARKUP", "aliases": [], "category": "Annotation", "description": "Creates review markup in the drawing.", "usage": "MARKUP", "example": "Add markup geometry and comments.", "tips": "Use with markup manager for team review.", "isFree": False},
    {"id": "markupmanager", "name": "MARKUPMANAGER", "aliases": [], "category": "Annotation", "description": "Manages drawing markup and review comments.", "usage": "MARKUPMANAGER", "example": "Browse and navigate markup entries.", "tips": "Track review cycles on shared projects.", "isFree": False},
    {"id": "meshmerge", "name": "MESHMERGE", "aliases": [], "category": "3D", "description": "Merges adjacent mesh faces.", "usage": "MESHMERGE", "example": "Select mesh faces to combine.", "tips": "Simplify mesh before export.", "isFree": False},
    {"id": "meshexplode", "name": "MESHEXPLODE", "aliases": [], "category": "3D", "description": "Explodes mesh objects into faces.", "usage": "MESHEXPLODE", "example": "Select mesh and explode level.", "tips": "Edit individual faces afterward.", "isFree": False},
    {"id": "meshprimitive", "name": "MESHPRIMITIVE", "aliases": [], "category": "3D", "description": "Creates basic mesh primitive shapes.", "usage": "MESHPRIMITIVE", "example": "Choose primitive type and size.", "tips": "Starting point for mesh modeling.", "isFree": False},
    {"id": "moveface", "name": "MOVEFACE", "aliases": [], "category": "3D", "description": "Moves a face on a 3D solid.", "usage": "MOVEFACE", "example": "Select face and displacement.", "tips": "Direct solid editing without booleans.", "isFree": False},
    {"id": "mredo", "name": "MREDO", "aliases": [], "category": "Settings & System", "description": "Redoes multiple UNDO operations.", "usage": "MREDO", "example": "Run after several UNDO commands.", "tips": "Restores a batch of undone steps.", "isFree": False},
    {"id": "multiple", "name": "MULTIPLE", "aliases": [], "category": "Settings & System", "description": "Repeats the next command until canceled.", "usage": "MULTIPLE", "example": "Type MULTIPLE then the command name.", "tips": "Avoids retyping repetitive commands.", "isFree": False},
    {"id": "navbar", "name": "NAVBAR", "aliases": [], "category": "View & Navigation", "description": "Shows or hides the navigation bar.", "usage": "NAVBAR", "example": "Toggle bar display in viewport.", "tips": "Quick access to orbit and walk tools.", "isFree": False},
    {"id": "offsetedge", "name": "OFFSETEDGE", "aliases": [], "category": "3D", "description": "Offsets an edge on a 3D solid.", "usage": "OFFSETEDGE", "example": "Select edge and offset distance.", "tips": "Useful for edge-based solid modeling.", "isFree": False},
    {"id": "osnap3d", "name": "OSNAP3D", "aliases": [], "category": "Settings & System", "description": "Sets running 3D object snaps.", "usage": "OSNAP3D", "example": "Enable vertex, edge, and face snaps.", "tips": "Essential for accurate 3D modeling picks.", "isFree": False},
    {"id": "partialopen", "name": "PARTIALOPEN", "aliases": [], "category": "Settings & System", "description": "Opens only selected layers from a large file.", "usage": "PARTIALOPEN", "example": "Choose layers to load.", "tips": "Improves performance on huge drawings.", "isFree": False},
    {"id": "pastespec", "name": "PASTESPEC", "aliases": [], "category": "Settings & System", "description": "Pastes clipboard data with format options.", "usage": "PASTESPEC", "example": "Choose paste type and insertion point.", "tips": "Control embedded Excel or image data.", "isFree": False},
    {"id": "plotstamp", "name": "PLOTSTAMP", "aliases": [], "category": "Settings & System", "description": "Adds configurable stamps to plotted output.", "usage": "PLOTSTAMP", "example": "Enable stamp with date and file name.", "tips": "Track submittals on printed sets.", "isFree": False},
    {"id": "pointcloud", "name": "POINTCLOUDMANAGER", "aliases": [], "category": "Blocks & References", "description": "Manages point cloud display and clipping.", "usage": "POINTCLOUDMANAGER", "example": "Adjust density and region settings.", "tips": "Lower density improves navigation speed.", "isFree": False},
    {"id": "preview", "name": "PREVIEW", "aliases": [], "category": "Settings & System", "description": "Previews the drawing as it will plot.", "usage": "PREVIEW", "example": "Run before sending sheets to plot.", "tips": "Catch scale and orientation mistakes early.", "isFree": False},
    {"id": "publishoptions", "name": "PUBLISHOPTIONS", "aliases": [], "category": "Settings & System", "description": "Sets default batch publish options.", "usage": "PUBLISHOPTIONS", "example": "Configure output folder and naming.", "tips": "Save time on recurring publish jobs.", "isFree": False},
    {"id": "qvlayout", "name": "QVLAYOUT", "aliases": [], "category": "View & Navigation", "description": "Creates a quick layout with a viewport.", "usage": "QVLAYOUT", "example": "Choose template and viewport scale.", "tips": "Rapid single-sheet setup.", "isFree": False},
    {"id": "redefine", "name": "REDEFINE", "aliases": [], "category": "Settings & System", "description": "Restores a built-in command that was undefined.", "usage": "REDEFINE", "example": "Enter command name to restore.", "tips": "Use after UNDEFINE blocked a command.", "isFree": False},
    {"id": "regen3", "name": "REGEN3", "aliases": [], "category": "View & Navigation", "description": "Regenerates drawing and rebuilds 3D display data.", "usage": "REGEN3", "example": "Run when 3D display looks wrong.", "tips": "Heavier than standard REGEN.", "isFree": False},
    {"id": "rendercrop", "name": "RENDERCROP", "aliases": [], "category": "3D", "description": "Renders only a cropped region of the view.", "usage": "RENDERCROP", "example": "Define crop window and render.", "tips": "Fast test renders of small areas.", "isFree": False},
    {"id": "renderpreset", "name": "RENDERPRESET", "aliases": [], "category": "3D", "description": "Manages stored render quality presets.", "usage": "RENDERPRESET", "example": "Save draft or high-quality presets.", "tips": "Draft presets iterate faster.", "isFree": False},
    {"id": "rotate3d", "name": "ROTATE3D", "aliases": [], "category": "3D", "description": "Rotates objects about a 3D axis.", "usage": "ROTATE3D", "example": "Select objects, axis, and angle.", "tips": "Command-line alternative to 3DROTATE.", "isFree": False},
    {"id": "securityoptions", "name": "SECURITYOPTIONS", "aliases": [], "category": "Settings & System", "description": "Sets drawing password and encryption options.", "usage": "SECURITYOPTIONS", "example": "Define open and modify passwords.", "tips": "Store passwords securely.", "isFree": False},
    {"id": "setbyblock", "name": "SETBYBLOCK", "aliases": ["SBB"], "category": "Layers & Properties", "description": "Sets selected object properties to ByBlock.", "usage": "SETBYBLOCK", "example": "Select objects inside block definitions.", "tips": "Prepare geometry for block creation.", "isFree": False},
    {"id": "setuv", "name": "SETUV", "aliases": [], "category": "3D", "description": "Adjusts material UV mapping on faces.", "usage": "SETUV", "example": "Select faces and adjust mapping.", "tips": "Fixes stretched render textures.", "isFree": False},
    {"id": "shadeplot", "name": "SHADEPLOT", "aliases": [], "category": "Settings & System", "description": "Plots using shaded viewport display.", "usage": "SHADEPLOT", "example": "Enable shaded plot in page setup.", "tips": "Presentation plots with materials.", "isFree": False},
    {"id": "share", "name": "SHARE", "aliases": [], "category": "Settings & System", "description": "Shares the drawing through cloud collaboration.", "usage": "SHARE", "example": "Choose share target and permissions.", "tips": "Requires a signed-in cloud account.", "isFree": False},
    {"id": "sheetset", "name": "SHEETSET", "aliases": ["SSM"], "category": "Settings & System", "description": "Manages organized sets of layout sheets.", "usage": "SHEETSET", "example": "Create set, add sheets, and publish.", "tips": "Standardize sheet numbering on large jobs.", "isFree": False},
    {"id": "snapang", "name": "SNAPANG", "aliases": [], "category": "Settings & System", "description": "Sets rotation angle for snap and grid.", "usage": "SNAPANG", "example": "Enter angle or pick two points.", "tips": "Align grid to angled building geometry.", "isFree": False},
    {"id": "snapbase", "name": "SNAPBASE", "aliases": [], "category": "Settings & System", "description": "Relocates snap and grid origin.", "usage": "SNAPBASE", "example": "Pick new base point.", "tips": "Use with SNAPANG for skewed grids.", "isFree": False},
    {"id": "solidcheck", "name": "SOLIDCHECK", "aliases": [], "category": "3D", "description": "Validates 3D solids for geometry errors.", "usage": "SOLIDCHECK", "example": "Select solids to inspect.", "tips": "Run before boolean operations on imports.", "isFree": False},
    {"id": "surfextract", "name": "SURFEXTRACT", "aliases": [], "category": "3D", "description": "Extracts faces from solids as surfaces.", "usage": "SURFEXTRACT", "example": "Select faces to extract.", "tips": "Edit complex faces independently.", "isFree": False},
    {"id": "surffillet", "name": "SURFFILLET", "aliases": [], "category": "3D", "description": "Creates a fillet surface between two surfaces.", "usage": "SURFFILLET", "example": "Select surfaces and radius.", "tips": "Smooth transitions in surface models.", "isFree": False},
    {"id": "surfextend", "name": "SURFEXTEND", "aliases": [], "category": "3D", "description": "Extends a surface to another edge or surface.", "usage": "SURFEXTEND", "example": "Select edge and extension distance.", "tips": "Closes gaps between surface bodies.", "isFree": False},
    {"id": "surfloft", "name": "SURFLOFT", "aliases": [], "category": "3D", "description": "Creates a lofted surface through cross sections.", "usage": "SURFLOFT", "example": "Select sections in order.", "tips": "Add guide curves to control shape.", "isFree": False},
    {"id": "surfrevolve", "name": "SURFREVOLVE", "aliases": [], "category": "3D", "description": "Creates a revolved surface from a profile.", "usage": "SURFREVOLVE", "example": "Select profile and revolution axis.", "tips": "Partial angles create open shells.", "isFree": False},
    {"id": "surfsweep", "name": "SURFSWEEP", "aliases": [], "category": "3D", "description": "Sweeps a profile along a path to create a surface.", "usage": "SURFSWEEP", "example": "Select profile and path.", "tips": "Surface alternative to SWEEP.", "isFree": False},
    {"id": "surftrim", "name": "SURFTRIM", "aliases": [], "category": "3D", "description": "Trims a surface using cutting objects.", "usage": "SURFTRIM", "example": "Select surface and cutters.", "tips": "Keep cutters simple for reliability.", "isFree": False},
    {"id": "sysvarmonitor", "name": "SYSVARMONITOR", "aliases": [], "category": "Settings & System", "description": "Alerts when monitored system variables change.", "usage": "SYSVARMONITOR", "example": "Add variables such as LTSCALE.", "tips": "Catch unexpected setting changes.", "isFree": False},
    {"id": "tableedit", "name": "TABLEEDIT", "aliases": [], "category": "Annotation", "description": "Edits table cells and structure.", "usage": "TABLEEDIT", "example": "Select table and modify cells.", "tips": "Double-click cells for in-place editing.", "isFree": False},
    {"id": "textalign", "name": "TEXTALIGN", "aliases": [], "category": "Annotation", "description": "Aligns text objects to references.", "usage": "TEXTALIGN", "example": "Select text and alignment target.", "tips": "Neaten notes on crowded details.", "isFree": False},
    {"id": "undefine", "name": "UNDEFINE", "aliases": [], "category": "Settings & System", "description": "Disables a command name in the session.", "usage": "UNDEFINE", "example": "Enter command to block.", "tips": "Use REDEFINE to restore it.", "isFree": False},
    {"id": "vlide", "name": "VLIDE", "aliases": [], "category": "Settings & System", "description": "Opens the Visual LISP integrated editor.", "usage": "VLIDE", "example": "Launch IDE to write LISP routines.", "tips": "For advanced customization.", "isFree": False},
    {"id": "vlload", "name": "VLLOAD", "aliases": [], "category": "Settings & System", "description": "Loads Visual LISP application files.", "usage": "VLLOAD", "example": "Select VLX or FAS file.", "tips": "Used with custom automation.", "isFree": False},
    {"id": "walkfly", "name": "WALKFLY", "aliases": [], "category": "View & Navigation", "description": "Switches between walk and fly navigation modes.", "usage": "WALKFLY", "example": "Toggle mode during 3D navigation.", "tips": "Walk keeps eye height fixed.", "isFree": False},
    {"id": "wmfin", "name": "WMFIN", "aliases": [], "category": "Settings & System", "description": "Imports a Windows metafile into the drawing.", "usage": "WMFIN", "example": "Select file and insertion point.", "tips": "Legacy vector import format.", "isFree": False},
    {"id": "workspace", "name": "WORKSPACE", "aliases": [], "category": "Settings & System", "description": "Switches between saved workspace layouts.", "usage": "WORKSPACE", "example": "Choose drafting or 3D workspace.", "tips": "Save workspace after arranging palettes.", "isFree": False},
    {"id": "wssave", "name": "WSSAVE", "aliases": [], "category": "Settings & System", "description": "Saves current UI layout as a workspace.", "usage": "WSSAVE", "example": "Enter workspace name.", "tips": "Create discipline-specific layouts.", "isFree": False},
    {"id": "xclipframe", "name": "XCLIPFRAME", "aliases": [], "category": "Blocks & References", "description": "Controls visibility of clip frame boundaries.", "usage": "XCLIPFRAME", "example": "Set frames on, off, or hidden.", "tips": "Hide frames before final plots.", "isFree": False},
    # Express Tools & legacy (still commonly searched)
    {"id": "breakline", "name": "BREAKLINE", "aliases": [], "category": "Drawing", "description": "Creates a break-line symbol at a chosen location.", "usage": "BREAKLINE", "example": "Specify break point and symbol size.", "tips": "Common for shortened views in details.", "isFree": False},
    {"id": "copym", "name": "COPYM", "aliases": [], "category": "Modifying", "description": "Copies objects multiple times with interactive placement.", "usage": "COPYM", "example": "Select objects and place repeated copies.", "tips": "Express tool for quick duplication.", "isFree": False},
    {"id": "extendedclip", "name": "CLIPIT", "aliases": [], "category": "Blocks & References", "description": "Clips blocks, xrefs, and images with a polyline boundary.", "usage": "CLIPIT", "example": "Select reference and clipping polyline.", "tips": "Express tool alternative to XCLIP.", "isFree": False},
    {"id": "fastext", "name": "FASTEXT", "aliases": [], "category": "Modifying", "description": "Extends objects to meet boundaries quickly.", "usage": "FASTEXT", "example": "Select objects to extend.", "tips": "Express tool for rapid cleanup.", "isFree": False},
    {"id": "fasttrim", "name": "FASTTRIM", "aliases": [], "category": "Modifying", "description": "Trims objects quickly without selecting cutting edges first.", "usage": "FASTTRIM", "example": "Select objects to trim.", "tips": "Express tool for fast editing sessions.", "isFree": False},
    {"id": "mocoros", "name": "MOCORO", "aliases": [], "category": "Modifying", "description": "Moves and copies objects in one combined operation.", "usage": "MOCORO", "example": "Select objects and define move/copy options.", "tips": "Express tool time-saver for layout work.", "isFree": False},
    {"id": "movecopy", "name": "MOVECOPY", "aliases": [], "category": "Modifying", "description": "Moves selected objects and optionally copies them.", "usage": "MOVECOPY", "example": "Select objects and displacement.", "tips": "Express tool combining move workflows.", "isFree": False},
    {"id": "rtext", "name": "RTEXT", "aliases": [], "category": "Annotation", "description": "Creates remote text linked to an external text file.", "usage": "RTEXT", "example": "Point to TXT file and place text.", "tips": "Update notes by editing the external file.", "isFree": False},
    {"id": "superhatch", "name": "SUPERHATCH", "aliases": [], "category": "Drawing", "description": "Creates hatches using images, blocks, or xref patterns.", "usage": "SUPERHATCH", "example": "Choose hatch type and boundary.", "tips": "Express tool for custom pattern fills.", "isFree": False},
    {"id": "textfit", "name": "TEXTFIT", "aliases": [], "category": "Annotation", "description": "Shrinks or stretches text to fit between two points.", "usage": "TEXTFIT", "example": "Select text and define fit points.", "tips": "Express tool for title block adjustments.", "isFree": False},
    {"id": "textmask", "name": "TEXTMASK", "aliases": [], "category": "Annotation", "description": "Masks text behind geometry using a wipeout.", "usage": "TEXTMASK", "example": "Select text to apply mask.", "tips": "Improves readability over hatches.", "isFree": False},
    {"id": "tframed", "name": "TFRAMES", "aliases": [], "category": "Annotation", "description": "Controls frame display for text and mtext objects.", "usage": "TFRAMES", "example": "Toggle frames on or off globally.", "tips": "Express tool for text frame visibility.", "isFree": False},
    {"id": "trimtext", "name": "TRIMTEXT", "aliases": [], "category": "Annotation", "description": "Trims text objects to fit within a boundary.", "usage": "TRIMTEXT", "example": "Select text and trimming edge.", "tips": "Express tool for crowded details.", "isFree": False},
    {"id": "chspaceex", "name": "CHSPACEX", "aliases": [], "category": "View & Navigation", "description": "Advanced object transfer between model and paper space.", "usage": "CHSPACEX", "example": "Select objects to change space context.", "tips": "Express tool variant of CHSPACE.", "isFree": False},
    {"id": "blockreplace", "name": "BLOCKREPLACE", "aliases": [], "category": "Blocks & References", "description": "Replaces one block reference with another globally.", "usage": "BLOCKREPLACE", "example": "Select source and destination block names.", "tips": "Express tool for symbol standardization.", "isFree": False},
    {"id": "copynested", "name": "COPYNESTED", "aliases": [], "category": "Blocks & References", "description": "Copies objects nested inside blocks or xrefs.", "usage": "COPYNESTED", "example": "Select nested object and new location.", "tips": "Similar workflow to NCOPY.", "isFree": False},
]

def main():
    with BASE.open() as f:
        data = json.load(f)

    existing_ids = {c["id"] for c in data["commands"]}
    existing_names = {c["name"] for c in data["commands"]}

    added = []
    for cmd in EXTRA:
        if cmd["id"] in existing_ids or cmd["name"] in existing_names:
            continue
        added.append(cmd)
        existing_ids.add(cmd["id"])
        existing_names.add(cmd["name"])

    data["commands"].extend(added)
    data["commands"].sort(key=lambda c: c["name"])

    with BASE.open("w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    size_kb = BASE.stat().st_size / 1024
    total = len(data["commands"])
    free = sum(1 for c in data["commands"] if c["isFree"])
    print(f"added={len(added)} total={total} free={free} pro={total-free} size_kb={size_kb:.1f}")

if __name__ == "__main__":
    main()
