#!/bin/bash
set -euo pipefail

echo "=============================================="
echo " Cloudflare Pages setup (private GitHub + free)"
echo "=============================================="
echo ""
echo "Your support site files live in: docs/"
echo "Deploy target project: cad-commands"
echo "Custom domain: palladiumcompass.com"
echo ""

if [[ -z "${CLOUDFLARE_API_TOKEN:-}" || -z "${CLOUDFLARE_ACCOUNT_ID:-}" ]]; then
  echo "STEP 1 — Cloudflare API token"
  echo "  1. Open: https://dash.cloudflare.com/profile/api-tokens"
  echo "  2. Create token → Edit Cloudflare Workers template"
  echo "  3. Permissions: Account → Cloudflare Pages → Edit"
  echo "  4. Copy the token"
  echo ""
  echo "STEP 2 — Account ID"
  echo "  Open: https://dash.cloudflare.com/"
  echo "  Copy Account ID from the right sidebar"
  echo ""
  echo "STEP 3 — GitHub secrets (repo: Palladium-Compass-LLC/cad-commands)"
  echo "  Open: https://github.com/Palladium-Compass-LLC/cad-commands/settings/secrets/actions"
  echo "  Add:"
  echo "    CLOUDFLARE_API_TOKEN"
  echo "    CLOUDFLARE_ACCOUNT_ID"
  echo ""
  echo "STEP 4 — Trigger deploy"
  echo "  Push to main, or run the workflow manually:"
  echo "  https://github.com/Palladium-Compass-LLC/cad-commands/actions"
  echo ""
  echo "STEP 5 — Custom domain in Cloudflare"
  echo "  Pages → cad-commands → Custom domains → Set up a domain"
  echo "  Add: palladiumcompass.com and www.palladiumcompass.com"
  echo "  (If DNS is already on Cloudflare, records are added automatically.)"
  echo ""
  echo "STEP 6 — Turn OFF GitHub Pages"
  echo "  https://github.com/Palladium-Compass-LLC/cad-commands/settings/pages"
  echo "  Set Source to None"
  echo ""
  echo "STEP 7 — Make repo private"
  echo "  https://github.com/Palladium-Compass-LLC/cad-commands/settings"
  echo "  Danger Zone → Change visibility → Private"
  echo ""
  echo "Verify:"
  echo "  https://cad-commands.pages.dev"
  echo "  https://palladiumcompass.com/"
  echo "  https://palladiumcompass.com/privacy.html"
  exit 0
fi

echo "Testing Cloudflare credentials..."
account_name="$(curl -fsS "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}" \
  -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
  -H "Content-Type: application/json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["result"]["name"])')"
echo "Connected to Cloudflare account: ${account_name}"
echo ""
echo "Add GitHub secrets if you have not already, then push to main to deploy."
